const colors = [
  "red",
  "blue",
  "green",
  "yellow",
  "orange",
  "purple",
  "pink",
  "brown",
  "black",
  "white",
  "gray",
  //   "cyan",
  //   "magenta",
  //   "lime",
  //   "olive",
  //   "maroon",
  //   "navy",
  //   "teal",
  //   "aqua",
  //   "fuchsia",
  //   "silver",
  //   "gold",
  //   "indigo",
  //   "violet",
  //   "coral",
  //   "khaki",
  //   "plum",
  //   "salmon",
  //   "tan",
  //   "turquoise",
  //   "wheat",
  //   "beige",
  //   "azure",
  //   "lavender",
  //   "mint",
  //   "rose",
  //   "apricot",
  //   "lilac",
  //   "periwinkle",
  //   "banana",
  //   "cantaloupe",
  //   "carnation",
  //   "cinnamon",
  //   "daffodil",
  //   "dandelion",
  //   "fuchsia",
];

module.exports.getColor = () => {
  return colors[Math.round(Math.random() * (colors.length - 1))];
};
